CREATE TABLE TBL_TIPO_VEICULO (
	IDTIPOVEICULO INT PRIMARY KEY AUTO_INCREMENT,
	TIP_NOME VARCHAR(20) NOT NULL
	
);

INSERT INTO TBL_TIPO_VEICULO (TIP_NOME) VALUES ('CARRO');
INSERT INTO TBL_TIPO_VEICULO (TIP_NOME) VALUES ('MOTO');


CREATE TABLE TBL_MARCA (
	IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
	MAR_NOME VARCHAR (40) NOT NULL,
	ID_TIPO INT,
	FOREIGN KEY (ID_TIPO)
	REFERENCES TBL_TIPO_VEICULO(IDTIPOVEICULO)		 
);

INSERT INTO TBL_MARCA (MAR_NOME,ID_TIPO) VALUES ('PEUGEOT',1);
INSERT INTO TBL_MARCA (MAR_NOME,ID_TIPO) VALUES ('HONDA',2);



CREATE TABLE TBL_COR (
	IDCOR INT PRIMARY KEY AUTO_INCREMENT,	
	COR_NOME VARCHAR(20) NOT NULL
);

INSERT INTO TBL_COR (COR_NOME) VALUES ('PRETO');
INSERT INTO TBL_COR (COR_NOME) VALUES ('BRANCO');



CREATE TABLE TBL_MODELO (
	IDMODELO INT PRIMARY KEY AUTO_INCREMENT,
	MOD_NOME VARCHAR(40) NOT NULL,
	ID_MARCA INT,
	ID_TIPO INT,
    MOD_ANO VARCHAR(10) NOT NULL,
    ID_MENSALISTA INT,
	ID_COR INT,
    MOD_PLACA VARCHAR(20),
	FOREIGN KEY (ID_COR)
	REFERENCES TBL_COR(ID_COR),
    FOREIGN KEY (ID_MENSALISTA)
	REFERENCES TBL_MENSALISTA(IDMENSALISTA),
	FOREIGN KEY (ID_MARCA)
	REFERENCES TBL_MARCA(IDMARCA),
    FOREIGN KEY (ID_TIPO)
	REFERENCES TBL_TIPO_VEICULO(IDTIPOVEICULO)
		
);

INSERT INTO TBL_MODELO (MOD_NOME,ID_MARCA,ID_TIPO,MOD_ANO,ID_MENSALISTA,ID_COR,MOD_PLACA) 
VALUES ('207',1,1,'2010',1,1,'ENS-9758');
INSERT INTO TBL_MODELO (MOD_NOME,ID_MARCA,ID_TIPO,MOD_ANO,ID_MENSALISTA,ID_COR,MOD_PLACA) 
VALUES ('Hornet',2,2,'2018',1,2,'HON-1234');



CREATE TABLE TBL_MENSALISTA (
	IDMENSALISTA INT PRIMARY KEY AUTO_INCREMENT,
	MEN_NOME VARCHAR(100) NOT NULL,
	MEN_SEXO ENUM ('M' , 'F'),
	MEN_DATA_NASC DATE NOT NULL,
	MEN_CPF VARCHAR(20),
	MEN_DATA_CAD  TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
	
);


INSERT INTO TBL_MENSALISTA (MEN_NOME,MEN_SEXO,MEN_DATA_NASC,MEN_CPF) 
VALUES ('João Paulo Ferreira da Silva','M','1995/09/11','44634252805');


 CREATE TABLE TBL_ESTADO  (
	IDESTADO INT PRIMARY KEY AUTO_INCREMENT,
	EST_NOME VARCHAR(30) UNIQUE NOT NULL,
	EST_SIG VARCHAR(4) NOT NULL
);


INSERT INTO TBL_ESTADO (EST_NOME,EST_SIG) VALUES ('São Paulo','SP');


CREATE TABLE TBL_CIDADE (
	IDCIDADE INT PRIMARY KEY AUTO_INCREMENT,
	CID_NOME  VARCHAR(40)  NOT NULL,
	ID_ESTADO INT,
	FOREIGN KEY(ID_ESTADO)
	REFERENCES TBL_ESTADO(IDESTADO)
);

INSERT INTO TBL_CIDADE (CID_NOME,ID_ESTADO) VALUES ('Guarulhos',1);


CREATE TABLE TBL_ENDERECO (
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	END_LOGRADOURO VARCHAR(100) NOT NULL,
	END_NUMERO VARCHAR(10),
    END_BAIRRO VARCHAR(50) NOT NULL,
    END_CEP VARCHAR(20),
    END_COMPLEMENTO VARCHAR(100),
	ID_ESTADO INT,
	ID_CIDADE INT,
    ID_MENSALISTA INT,
	FOREIGN KEY(ID_ESTADO)
	REFERENCES TBL_ESTADO(IDESTADO),
	FOREIGN KEY(ID_CIDADE)
	REFERENCES TBL_CIDADE(IDCIDADE),
    FOREIGN KEY(ID_MENSALISTA)
	REFERENCES TBL_MENSALISTA(IDMENSALISTA)
);

INSERT INTO TBL_ENDERECO (END_LOGRADOURO,END_NUMERO,END_BAIRRO,END_CEP,END_COMPLEMENTO,ID_ESTADO,ID_CIDADE,ID_MENSALISTA)
 VALUES ('Av. Dois','17','Jardim Tranquilidade','07051220','Próximo ao estadio do flamenguinho de Guarulhos',1,1,1);


CREATE TABLE TBL_FORMA_PGTO (
	IDFORMAPGTO INT PRIMARY KEY AUTO_INCREMENT,
	FORM_NOME VARCHAR(50) NOT NULL

);

INSERT INTO TBL_FORMA_PGTO (FORM_NOME) VALUES('CARTÃO DE CRÉDITO');
INSERT INTO TBL_FORMA_PGTO (FORM_NOME) VALUES('CARTÃO DE DEBITO');
INSERT INTO TBL_FORMA_PGTO (FORM_NOME) VALUES('DINHEIRO');


CREATE TABLE TBL_TIPO_COBRANCA (
	IDTIPOCOBRANCA INT PRIMARY KEY AUTO_INCREMENT,
	TIP_COBRANCA VARCHAR(50) NOT NULL

);

INSERT INTO TBL_TIPO_COBRANCA (TIP_COBRANCA) VALUES('AVULSO');
INSERT INTO TBL_TIPO_COBRANCA (TIP_COBRANCA) VALUES('CORTESIA');
INSERT INTO TBL_TIPO_COBRANCA (TIP_COBRANCA) VALUES('MENSALISTA');


CREATE TABLE TBL_COBRANCA (
	IDCOBRANCA INT PRIMARY KEY AUTO_INCREMENT,
	COB_PLACA VARCHAR(50) NOT NULL,
	COB_DATA_ENT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    COB_DATA_SAI DATETIME,
    COB_VALOR DECIMAL(10,2),
    COB_OBS VARCHAR(150),
    ID_TIPOCOBRANCA INT,
	ID_FORMAPGTO INT,
    ID_MENSALISTA INT,
	FOREIGN KEY(ID_FORMAPGTO)
	REFERENCES TBL_FORMA_PGTO(IDFORMAPGTO),
    FOREIGN KEY(ID_TIPOCOBRANCA)
	REFERENCES TBL_TIPO_COBRANCA(IDTIPOCOBRANCA),
    FOREIGN KEY(ID_MENSALISTA)
	REFERENCES TBL_MENSALISTA(IDMENSALISTA)
	
);

/*Script de entrada - Avulso*/
INSERT INTO TBL_COBRANCA (COB_PLACA) VALUES('abc-1234');

CREATE TABLE TBL_ACESSO_NIVEL (
	IDACESSONIVEL CHAR(1) PRIMARY KEY NOT NULL,
	ACE_NOMENIVEL VARCHAR(100) NOT NULL
    
);

SET SQL_SAFE_UPDATES=0;


INSERT INTO TBL_ACESSO_NIVEL (IDACESSONIVEL,ACE_NOMENIVEL) VALUES('G','GERENTE');
INSERT INTO TBL_ACESSO_NIVEL (IDACESSONIVEL,ACE_NOMENIVEL) VALUES('O','OPERADOR');


CREATE TABLE TBL_USUARIO (
	IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
	USU_NOME VARCHAR(30) NOT NULL,
	USU_LOGIN VARCHAR (20) NOT NULL,
	USU_SENHA VARCHAR(100) NOT NULL,
	ID_ACESSONIVEL CHAR(1),
	FOREIGN KEY(ID_ACESSONIVEL)
	REFERENCES TBL_ACESSO_NIVEL(IDACESSONIVEL)
	
);

INSERT INTO TBL_USUARIO (USU_NOME,USU_LOGIN,USU_SENHA,ID_ACESSONIVEL)
 VALUES('João Paulo Ferreira da Silva','joao.silva',(SELECT md5('Controle78')),'G');



